<a href="https://colab.research.google.com/github/Alejohenao-8/python/blob/main/Laboratorio_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
#Ejercicio de práctica 1.
#1. Salud Digital y Análisis de Datos de Pacientes

import pandas as pd

# Crear el DataFrame inicial
data = {
    'Nombre': ['Carlos', 'Ana', 'Luis', 'Pedro', 'María', None],
    'Edad': [34, 29, None, 45, 25, 33],
    'Fecha_Ingreso': ['2021-01-15', '2020/03/12', '2022-07-01', '2021/12/01', '2021-05-20', '2020-03-12'],
    'Resultado_Prueba': ['Positivo', 'Negativo', 'Positivo', 'Positivo', 'Negativo', 'Negativo']
}

df = pd.DataFrame(data)
print("Datos de pacientes:")
print(df)
print("\n")

# 1. Rellenar valores faltantes en la columna 'Nombre' (si fuera necesario, se podría llenar con "Desconocido")
df['Nombre'].fillna('Desconocido', inplace=True)
print(" Rellenar valores faltantes en la columna 'Nombre' por Desconocido")
print(df)
print("\n")

# 2. Rellenar valores faltantes en la columna 'Edad' con la media de las edades
df['Edad'].fillna(df['Edad'].mean(), inplace=True)
print("valores faltantes en la columna 'Edad' con la media de las edades")
print(df)
print("\n")

# 3. Estandarizar el formato de la columna 'Fecha_Ingreso' a YYYY-MM-DD
df['Fecha_Ingreso'] = df['Fecha_Ingreso'].str.replace('/', '-')
print("Estandarizar el formato de la columna 'Fecha_Ingreso' a YYYY-MM-DD")
print(df)
print("\n")

Datos de pacientes:
   Nombre  Edad Fecha_Ingreso Resultado_Prueba
0  Carlos  34.0    2021-01-15         Positivo
1     Ana  29.0    2020/03/12         Negativo
2    Luis   NaN    2022-07-01         Positivo
3   Pedro  45.0    2021/12/01         Positivo
4   María  25.0    2021-05-20         Negativo
5    None  33.0    2020-03-12         Negativo


 Rellenar valores faltantes en la columna 'Nombre' por Desconocido
        Nombre  Edad Fecha_Ingreso Resultado_Prueba
0       Carlos  34.0    2021-01-15         Positivo
1          Ana  29.0    2020/03/12         Negativo
2         Luis   NaN    2022-07-01         Positivo
3        Pedro  45.0    2021/12/01         Positivo
4        María  25.0    2021-05-20         Negativo
5  Desconocido  33.0    2020-03-12         Negativo


valores faltantes en la columna 'Edad' con la media de las edades
        Nombre  Edad Fecha_Ingreso Resultado_Prueba
0       Carlos  34.0    2021-01-15         Positivo
1          Ana  29.0    2020/03/12         Negativo
2         Luis  33.2    2022-07-01         Positivo
3        Pedro  45.0    2021/12/01         Positivo
4        María  25.0    2021-05-20         Negativo
5  Desconocido  33.0    2020-03-12         Negativo


Estandarizar el formato de la columna 'Fecha_Ingreso' a YYYY-MM-DD
        Nombre  Edad Fecha_Ingreso Resultado_Prueba
0       Carlos  34.0    2021-01-15         Positivo
1          Ana  29.0    2020-03-12         Negativo
2         Luis  33.2    2022-07-01         Positivo
3        Pedro  45.0    2021-12-01         Positivo
4        María  25.0    2021-05-20         Negativo
5  Desconocido  33.0    2020-03-12         Negativo

<ipython-input-38-df3c7c4d5ecd>:17: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Nombre'].fillna('Desconocido', inplace=True)
<ipython-input-38-df3c7c4d5ecd>:23: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Edad'].fillna(df['Edad'].mean(), inplace=True)

In [45]:
#2. Comercio Electrónico y Recomendaciones Personalizadas

import pandas as pd

# Datos iniciales
data = {
    'Cliente_ID': [1, 2, 3, 4, 5],
    'Producto': ['A', 'B', 'C', 'D', 'E'],
    'Cantidad': [10, 20, None, 5, 15],
    'Precio': ['100', '200$', '300', 'cuatrocientos', '500'],
    'Fecha_Transaccion': ['2023-01-15', '2023/02/20', '2023-03-25', '2023/04/30', '2023-05-10']
}

# Crear el DataFrame
df = pd.DataFrame(data)
print("Datos iniciales:")
print(df)
print("\n")

# Paso 1: Rellenar valores faltantes en la columna 'Cantidad'
# Rellenamos con la media de las cantidades
df['Cantidad'].fillna(df['Cantidad'].mean(), inplace=True)

print("valores faltantes en la columna 'Cantidad' con la media de las cantidades")
print(df)
print("\n")

# Paso 2: Limpiar y convertir la columna 'Precio' a valores numéricos
# Remover símbolos y textos y convertir a número, colocando NaN en caso de error
df['Precio'] = pd.to_numeric(df['Precio'].replace({'\$': '', 'cuatrocientos': '400'}, regex=True), errors='coerce')
print("Limpiar y convertir la columna 'Precio' a valores numéricos")
print(df)
print("\n")

# Paso 3: Estandarizar el formato de la columna 'Fecha_Transaccion' a YYYY-MM-DD
# Reemplazamos '/' por '-' y luego convertimos a formato datetime
df['Fecha_Transaccion'] = pd.to_datetime(df['Fecha_Transaccion'].str.replace('/', '-'), errors='coerce').dt.strftime('%Y-%m-%d')
print("Estandarizar el formato de la columna 'Fecha_Transaccion' a YYYY-MM-DD")
print(df)
print("\n")

Datos iniciales:
   Cliente_ID Producto  Cantidad         Precio Fecha_Transaccion
0           1        A      10.0            100        2023-01-15
1           2        B      20.0           200$        2023/02/20
2           3        C       NaN            300        2023-03-25
3           4        D       5.0  cuatrocientos        2023/04/30
4           5        E      15.0            500        2023-05-10


valores faltantes en la columna 'Cantidad' con la media de las cantidades
   Cliente_ID Producto  Cantidad         Precio Fecha_Transaccion
0           1        A      10.0            100        2023-01-15
1           2        B      20.0           200$        2023/02/20
2           3        C      12.5            300        2023-03-25
3           4        D       5.0  cuatrocientos        2023/04/30
4           5        E      15.0            500        2023-05-10


Limpiar y convertir la columna 'Precio' a valores numéricos
   Cliente_ID Producto  Cantidad  Precio Fecha_Transaccion
0           1        A      10.0     100        2023-01-15
1           2        B      20.0     200        2023/02/20
2           3        C      12.5     300        2023-03-25
3           4        D       5.0     400        2023/04/30
4           5        E      15.0     500        2023-05-10


Estandarizar el formato de la columna 'Fecha_Transaccion' a YYYY-MM-DD
   Cliente_ID Producto  Cantidad  Precio Fecha_Transaccion
0           1        A      10.0     100        2023-01-15
1           2        B      20.0     200        2023-02-20
2           3        C      12.5     300        2023-03-25
3           4        D       5.0     400        2023-04-30
4           5        E      15.0     500        2023-05-10

<ipython-input-45-be2ccaa662dd>:22: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Cantidad'].fillna(df['Cantidad'].mean(), inplace=True)

In [26]:
#Escenario: eres un analista de datos en una pequeña empresa que está recopilando información sobre sus clientes.
#Tu objetivo es limpiar los datos para que estén listos para el análisis, aplicando las siguientes técnicas:
import pandas as pd

data = {
    'Nombre': ['Juan', 'Maria', 'Pedro', 'Ana', 'Luisa', 'Carlos', 'Juan'],
    'Edad': [25, 30, None, 29, 28, 200, 25],
    'Email': ['juan@mail.com', 'maria@mail.com', 'pedro@mail.com', 'ana@mail.com', 'luisa@mail.com', 'carlos@mail.com', 'juan@mail.com'],
    'Pais': ['colombia', 'Colombia', 'Mexico', 'Argentina', 'Colombia', 'Brazil', 'colombia'],
    'Genero': ['M', 'F', 'H', 'F', 'Femenino', 'M', 'M'],
    'Visitas': [5, 7, 6, 4, 8, 2, 5]
}

df = pd.DataFrame(data)

print("Datos iniciales:")
print(df)
print("\n")

print("Columna 'Edad' después de rellenar valores faltantes:")
# Paso 3: Rellenar valores faltantes
df['Edad'].fillna(df['Edad'].mean(), inplace=True)

# Imprimimos la columna Edad para verificar que ya no hay valores faltantes
print(df)
print("\n")
# Paso 4: Eliminar duplicados
df.drop_duplicates(inplace=True)
print("\nEliminar duplicados")
print(df)
print("\n")

# Paso 5: Estandarizar los valores de las columnas
# Estandarizar el género
df['Genero'] = df['Genero'].replace({
    'M': 'Masculino',
    'H': 'Masculino',
    'F': 'Femenino',
    'Femenino': 'Femenino'
})

print("\nEstandarizar los valores de las columnas: género")
print(df)
print("\n")

# Estandarizar el país (asegurar que esté en mayúsculas)
df['Pais'] = df['Pais'].str.capitalize()

print("\nEstandarizar el país:")
print(df)
print("\n")

# Paso 6: Corregir valores inválidos (como la edad de 200 años).
# Asumimos que la edad máxima razonable es 100 años
df['Edad'] = df['Edad'].apply(lambda x: x if x < 100 else df['Edad'].mean())
print("\nCorregir valores inválidos:(como la edad de 200 años).")
print(df)

Datos iniciales:
   Nombre   Edad            Email       Pais    Genero  Visitas
0    Juan   25.0    juan@mail.com   colombia         M        5
1   Maria   30.0   maria@mail.com   Colombia         F        7
2   Pedro    NaN   pedro@mail.com     Mexico         H        6
3     Ana   29.0     ana@mail.com  Argentina         F        4
4   Luisa   28.0   luisa@mail.com   Colombia  Femenino        8
5  Carlos  200.0  carlos@mail.com     Brazil         M        2
6    Juan   25.0    juan@mail.com   colombia         M        5


Columna 'Edad' después de rellenar valores faltantes:
   Nombre        Edad            Email       Pais    Genero  Visitas
0    Juan   25.000000    juan@mail.com   colombia         M        5
1   Maria   30.000000   maria@mail.com   Colombia         F        7
2   Pedro   56.166667   pedro@mail.com     Mexico         H        6
3     Ana   29.000000     ana@mail.com  Argentina         F        4
4   Luisa   28.000000   luisa@mail.com   Colombia  Femenino        8
5  Carlos  200.000000  carlos@mail.com     Brazil         M        2
6    Juan   25.000000    juan@mail.com   colombia         M        5



Eliminar duplicados
   Nombre        Edad            Email       Pais    Genero  Visitas
0    Juan   25.000000    juan@mail.com   colombia         M        5
1   Maria   30.000000   maria@mail.com   Colombia         F        7
2   Pedro   56.166667   pedro@mail.com     Mexico         H        6
3     Ana   29.000000     ana@mail.com  Argentina         F        4
4   Luisa   28.000000   luisa@mail.com   Colombia  Femenino        8
5  Carlos  200.000000  carlos@mail.com     Brazil         M        2



Estandarizar los valores de las columnas: género
   Nombre        Edad            Email       Pais     Genero  Visitas
0    Juan   25.000000    juan@mail.com   colombia  Masculino        5
1   Maria   30.000000   maria@mail.com   Colombia   Femenino        7
2   Pedro   56.166667   pedro@mail.com     Mexico  Masculino        6
3     Ana   29.000000     ana@mail.com  Argentina   Femenino        4
4   Luisa   28.000000   luisa@mail.com   Colombia   Femenino        8
5  Carlos  200.000000  carlos@mail.com     Brazil  Masculino        2



Estandarizar el país:
   Nombre        Edad            Email       Pais     Genero  Visitas
0    Juan   25.000000    juan@mail.com   Colombia  Masculino        5
1   Maria   30.000000   maria@mail.com   Colombia   Femenino        7
2   Pedro   56.166667   pedro@mail.com     Mexico  Masculino        6
3     Ana   29.000000     ana@mail.com  Argentina   Femenino        4
4   Luisa   28.000000   luisa@mail.com   Colombia   Femenino        8
5  Carlos  200.000000  carlos@mail.com     Brazil  Masculino        2



Corregir valores inválidos:(como la edad de 200 años).
   Nombre       Edad            Email       Pais     Genero  Visitas
0    Juan  25.000000    juan@mail.com   Colombia  Masculino        5
1   Maria  30.000000   maria@mail.com   Colombia   Femenino        7
2   Pedro  56.166667   pedro@mail.com     Mexico  Masculino        6
3     Ana  29.000000     ana@mail.com  Argentina   Femenino        4
4   Luisa  28.000000   luisa@mail.com   Colombia   Femenino        8
5  Carlos  61.361111  carlos@mail.com     Brazil  Masculino        2

<ipython-input-26-3ed85720dde0>:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Edad'].fillna(df['Edad'].mean(), inplace=True)